platform :ios, '9.0'

target 'benhvien_app_v2' do
  use_frameworks!
  pod 'MBProgressHUD', '~> 1.0'
  pod 'PureLayout', '~> 3.0'
  pod 'IQKeyboardManager'
  pod 'IQDropDownTextField', '~> 1.1'
  pod 'KASlideShow', '~> 3.0'
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'OCGoogleDirectionsAPI'
  pod 'HNKGooglePlacesAutocomplete', '~> 1.2'
  pod 'NSUserDefaults+Utility', '~> 0.1'
end

